### ISSUE TITLE
Fix mojibake

### ISSUE THREAD

**Issue by ericjtaylor** [Hipnosis183/JM-Server#1]
Love this project and really appreciate it.

The READY, GO on game start is [mojibake](https://en.wikipedia.org/wiki/Mojibake) for me. Maybe other stuff too, I haven't looked thoroughly. Correct display without mojibake can be seen [here](https://www.youtube.com/watch?v=uqHrOwZfKj8).

I seem to remember this was an issue back in the day as well. The workaround was to install applocale.msi but Microsoft has dropped support and it appears that even if you install it, it no longer works on modern Windows.

Is there a known workaround? Or failing that, perhaps we can hack the (what I assume is) [Shift JIS](https://en.wikipedia.org/wiki/Shift_JIS) to something that works on modern systems?

**Comment by Hipnosis183** [comment]
Hey @ericjtaylor, glad you are enjoying it.

The client needs to run under a japanese system locale to display the "READY" and "GO" text, as well as the cursor/selector in the rankings properly. There are multiple applications out there that can solve the problem, but I've personally used [Locale Emulator](https://pooi.moe/Locale-Emulator/) during development.

I don't plan to include a built-in solution since that's way out of the scope of the project, and can be solved easily with external applications like the one described above. Still, I should probably update the readme at some point and mention the issue with the solution.
